version: "3.9"
services:
  web:
    build: ./backend
    command: gunicorn fraud_detection.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
  worker:
    build: ./backend
    command: celery -A fraud_detection worker --loglevel=info
    depends_on:
      - web
      - redis
  redis:
    image: redis:7
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud
      POSTGRES_DB: frauddb
    ports:
      - "5432:5432"
  scorer:
    build: ./ml_scorer
    ports:
      - "8081:8081"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
