# Generated by Django 4.2.7 on 2025-10-22 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('threshold', 'Пороговое правило'), ('pattern', 'Паттерн'), ('composite', 'Составное правило'), ('ml', 'ML правило')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pattern_config', models.JSONField(blank=True, null=True)),
                ('composite_rules', models.JSONField(blank=True, null=True)),
                ('ml_model_path', models.CharField(blank=True, max_length=500)),
                ('ml_threshold', models.FloatField(default=0.8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('from_account', models.CharField(max_length=255)),
                ('to_account', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Завершена'), ('suspicious', 'Подозрительная')], default='pending', max_length=20)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_fraud', models.BooleanField(default=False)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['correlation_id'], name='app_transac_correla_b09c98_idx'), models.Index(fields=['timestamp'], name='app_transac_timesta_4caf6f_idx'), models.Index(fields=['status'], name='app_transac_status_bd60d3_idx')],
            },
        ),
    ]
