# Generated by Django 4.2.7 on 2025-10-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudRule',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='app_transac_correla_b09c98_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='app_transac_timesta_4caf6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='app_transac_status_bd60d3_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='processed_at',
        ),
    ]
