# Generated by Django 4.2.7 on 2025-10-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_fraudrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('threshold', 'Пороговое правило'), ('pattern', 'Паттерн'), ('composite', 'Составное правило'), ('ml', 'ML правило')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pattern_config', models.JSONField(blank=True, null=True)),
                ('composite_rules', models.JSONField(blank=True, null=True)),
                ('ml_model_path', models.CharField(blank=True, max_length=500)),
                ('ml_threshold', models.FloatField(default=0.8)),
            ],
        ),
    ]
