# Generated by Django 4.2.7 on 2025-10-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fraudrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraudrule',
            name='composite_rules',
        ),
        migrations.RemoveField(
            model_name='fraudrule',
            name='ml_model_path',
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='composite_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=50000, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='nighttime_end',
            field=models.TimeField(blank=True, default='06:00:00', null=True),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='nighttime_start',
            field=models.TimeField(blank=True, default='22:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='fraudrule',
            name='pattern_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
