# Generated by Django 4.2.7 on 2025-10-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_fraudrule_composite_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_processed', models.IntegerField(default=0)),
                ('total_suspicious', models.IntegerField(default=0)),
                ('total_fraud', models.IntegerField(default=0)),
                ('avg_processing_time', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FraudCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('total_rules_checked', models.IntegerField(default=0)),
                ('triggered_rules', models.JSONField(default=list)),
                ('final_score', models.FloatField(default=0.0)),
                ('details', models.JSONField(default=dict)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_check', to='app.transaction')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
